T1.1:Enter the integer:1
T1.2:Enter the integer:2
T1.2:Enter the integer:3
T1.2:Enter the integer:4
T1.2:Enter the integer:5
T1.2:Enter the integer:6
T1.2:Enter the integer:7
T1.2:Enter the integer:8
T1.2:Enter the integer:9
T1.2:Enter the integer:10
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T1:Pipe is Full,wait to get empty....
T2:Signal....
T1:Pipe is Full,wait to get empty....
T2:read data is:1
T1.2:Enter the integer:1
T1:Pipe is Full,wait to get empty....
T2:read data is:2
T1.2:Enter the integer:9
T1:Pipe is Full,wait to get empty....
T2:read data is:3
T1.2:Enter the integer:8
T1:Pipe is Full,wait to get empty....
T2:read data is:4
T1.2:Enter the integer:7
T1:Pipe is Full,wait to get empty....
T2:read data is:5
T1.2:Enter the integer:6
T1:Pipe is Full,wait to get empty....
T2:read data is:6
T1.2:Enter the integer:5
T1:Pipe is Full,wait to get empty....
T2:read data is:7
T1.2:Enter the integer:4
T1:Pipe is Full,wait to get empty....
T2:read data is:8
T1.2:Enter the integer:3
T1:Pipe is Full,wait to get empty....
T2:read data is:9
T1.2:Enter the integer:2
T1:Pipe is Full,wait to get empty....
T2:read data is:10
T1.2:Enter the integer:1
T1:Pipe is Full,wait to get empty....
T2:read data is:1
T1.2:Enter the integer:0
T1:Pipe is Full,wait to get empty....
T2:read data is:9
T1.2:Enter the integer:^C
